<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'name' => 'E-mail',
                'slug' => 'email',
                'icon' => "\u{1F4E7}",
                'description' => 'Profesionálny e-mail s vlastnou doménou. Webmail, IMAP/SMTP, mobilné aplikácie, antispam a antivirus ochrana.',
                'features' => ['Vlastná doména @vašafirma.sk', 'Neobmedzené schránky', 'Mobilné aplikácie', 'Antispam & antivirus'],
                'category' => 'communication',
                'sort_order' => 1,
            ],
            [
                'name' => 'Calendar',
                'slug' => 'calendar',
                'icon' => "\u{1F4C5}",
                'description' => 'Zdieľané kalendáre pre tím, udalosti, pripomienky, pozvánky na stretnutia. Sync s iOS, Android, desktop aplikáciami.',
                'features' => ['Zdieľané kalendáre', 'Pozvánky na stretnutia', 'Pripomienky & notifikácie', 'Multi-device sync'],
                'category' => 'communication',
                'sort_order' => 2,
            ],
            [
                'name' => 'Drive',
                'slug' => 'drive',
                'icon' => "\u{1F4BE}",
                'description' => 'Cloudové úložisko pre súbory, fotky, dokumenty. Verzovanie, zdieľanie, prístupové práva, automatické zálohy.',
                'features' => ['Sync medzi zariadeniami', 'Verzovanie súborov', 'Zdieľanie & permissions', 'Automatické zálohy'],
                'category' => 'collaboration',
                'sort_order' => 3,
            ],
            [
                'name' => 'Docs',
                'slug' => 'docs',
                'icon' => "\u{1F4DD}",
                'description' => 'Textové dokumenty s real-time spoluprácou. Ako Google Docs, ale rýchlejšie a s lepšou MS Office kompatibilitou.',
                'features' => ['Real-time editing', 'Komentáre & track changes', 'Export PDF, DOCX', 'Šablóny dokumentov'],
                'category' => 'collaboration',
                'sort_order' => 4,
            ],
            [
                'name' => 'Sheets',
                'slug' => 'sheets',
                'icon' => "\u{1F4CA}",
                'description' => 'Tabuľky a spreadsheets s pokročilými vzorcami. Grafy, pivot tables, import/export Excel formátov.',
                'features' => ['Excel vzorce & funkcie', 'Grafy & vizualizácie', 'Pivot tables', 'Spolupráca v reálnom čase'],
                'category' => 'collaboration',
                'sort_order' => 5,
            ],
            [
                'name' => 'Slides',
                'slug' => 'slides',
                'icon' => "\u{1F4FD}",
                'description' => 'Prezentácie ako PowerPoint. Master slides, animácie, export do PDF/PPTX, presenter mode s poznámkami.',
                'features' => ['Animácie & transitions', 'Master slides & templates', 'Presenter mode', 'Export PDF/PPTX'],
                'category' => 'collaboration',
                'sort_order' => 6,
            ],
            [
                'name' => 'Chat',
                'slug' => 'chat',
                'icon' => "\u{1F4AC}",
                'description' => 'Team chat ako Slack. Kanály, súkromné správy, file sharing, integrácie. Desktop a mobilné aplikácie.',
                'features' => ['Channels & direct messages', 'File sharing & search', 'Desktop & mobile apps', 'Emoji & reactions'],
                'category' => 'communication',
                'sort_order' => 7,
            ],
            [
                'name' => 'Meets',
                'slug' => 'meets',
                'icon' => "\u{1F3A5}",
                'description' => 'Video konferencie do 100 účastníkov. Screen sharing, recording, chat v hovore. Bez časových limitov.',
                'features' => ['HD video & audio', 'Screen sharing', 'Recording meetings', 'Unlimited time'],
                'category' => 'communication',
                'sort_order' => 8,
            ],
            [
                'name' => 'Canvas',
                'slug' => 'canvas',
                'icon' => "\u{1F3A8}",
                'description' => 'Grafický editor ako Canva. Brand templates, plagáty, social media graphics. Component libraries pre konzistentný branding.',
                'features' => ['Brand design system', 'Social media templates', 'Vector & raster editing', 'Export PNG/SVG/PDF'],
                'category' => 'design',
                'sort_order' => 9,
            ],
            [
                'name' => 'Forms',
                'slug' => 'forms',
                'icon' => "\u{1F4CB}",
                'description' => 'Online formuláre a ankety. Drag & drop builder, podmienená logika, file uploads, export odpovedí, štatistiky.',
                'features' => ['28+ typov otázok', 'Conditional logic', 'File uploads', 'Analytics & export'],
                'category' => 'tools',
                'sort_order' => 10,
            ],
            [
                'name' => 'Booking',
                'slug' => 'booking',
                'icon' => "\u{1F5D3}",
                'description' => 'Rezervačný systém ako Calendly. Klienti si rezervujú termíny, automatické notifikácie, integrácia s kalendárom.',
                'features' => ['Nastaviteľná dostupnosť', 'Automatické emaily', 'Buffer time & limits', 'Custom booking forms'],
                'category' => 'tools',
                'sort_order' => 11,
            ],
            [
                'name' => 'Newsletter',
                'slug' => 'newsletter',
                'icon' => "\u{1F4E7}",
                'description' => 'Email marketing ako Mailchimp. Kampane, automatizácia, segmentácia, štatistiky (open rate, click rate), templates.',
                'features' => ['Drag & drop editor', 'Automation & drip campaigns', 'Segmentation & targeting', 'Analytics & A/B testing'],
                'category' => 'marketing',
                'sort_order' => 12,
            ],
            [
                'name' => 'Medias',
                'slug' => 'medias',
                'icon' => "\u{1F4F1}",
                'description' => 'Social media scheduling ako Buffer. Multi-platform posting (FB, IG, Twitter, LinkedIn), content calendar, analytics.',
                'features' => ['Multi-platform posting', 'Content calendar', 'Hashtag manager', 'Social analytics'],
                'category' => 'marketing',
                'sort_order' => 13,
            ],
            [
                'name' => 'Web',
                'slug' => 'web',
                'icon' => "\u{1F310}",
                'description' => 'Profesionálna webstránka na WordPress. Blog, SEO optimalizácia, mobilná responzivita, SSL certifikát.',
                'features' => ['WordPress CMS', 'Blog & SEO tools', 'Mobile responsive', 'SSL & HTTPS'],
                'category' => 'web',
                'sort_order' => 14,
            ],
            [
                'name' => 'E-shop',
                'slug' => 'eshop',
                'icon' => "\u{1F6D2}",
                'description' => 'Online obchod na WooCommerce. Produkty, košík, platobné brány (Stripe, PayPal), faktúry, email notifikácie.',
                'features' => ['Product catalog & variants', 'Payment gateways', 'Order management', 'Automatic invoicing'],
                'category' => 'web',
                'sort_order' => 15,
            ],
            [
                'name' => 'Community',
                'slug' => 'community',
                'icon' => "\u{1F465}",
                'description' => 'Online komunita ako Facebook Groups. Užívateľské profily, diskusné fóra, súkromné správy, activity feed.',
                'features' => ['Member profiles', 'Discussion forums', 'Private messaging', 'Activity streams'],
                'category' => 'community',
                'sort_order' => 16,
            ],
            [
                'name' => 'Education',
                'slug' => 'education',
                'icon' => "\u{1F393}",
                'description' => 'Online kurzy na LearnDash. Video lekcie, kvízy, certifikáty, sledovanie pokroku študentov, drip content.',
                'features' => ['Video lessons & modules', 'Quizzes & assignments', 'Certificates', 'Student progress tracking'],
                'category' => 'community',
                'sort_order' => 17,
            ],
            [
                'name' => 'Videos',
                'slug' => 'videos',
                'icon' => "\u{1F3AC}",
                'description' => 'Video hosting platforma. Adaptívny streaming, kategórie, watchlists, analytics, titulky, DRM ochrana obsahu.',
                'features' => ['HLS adaptive streaming', 'Video categories & series', 'Watch analytics', 'Subtitles & DRM'],
                'category' => 'media',
                'sort_order' => 18,
            ],
            [
                'name' => 'Webinars',
                'slug' => 'webinars',
                'icon' => "\u{1F4FA}",
                'description' => 'Živé webináre až pre 500 účastníkov. Breakout rooms, whiteboard, polls & quizzes, recording, livestream na YouTube.',
                'features' => ['Live streaming to 500+', 'Breakout rooms', 'Whiteboard & polls', 'Recording & replay'],
                'category' => 'media',
                'sort_order' => 19,
            ],
            [
                'name' => 'Stats',
                'slug' => 'stats',
                'icon' => "\u{1F4C8}",
                'description' => 'Web analytics ako Google Analytics. Návštevnosť, správanie užívateľov, konverzie, custom dashboardy. GDPR compliant.',
                'features' => ['Traffic analytics', 'User behavior tracking', 'Conversion funnels', 'Custom dashboards'],
                'category' => 'tools',
                'sort_order' => 20,
            ],
            [
                'name' => 'Billing',
                'slug' => 'billing',
                'icon' => "\u{1F4B3}",
                'description' => 'Fakturačný systém so Stripe integráciou. Automatické faktúry, recurring platby, daňové výpočty SK/EU, payment reports.',
                'features' => ['Stripe payment gateway', 'Automatic invoicing', 'Recurring subscriptions', 'Tax calculations SK/EU'],
                'category' => 'tools',
                'sort_order' => 21,
            ],
            [
                'name' => 'Passwords',
                'slug' => 'passwords',
                'icon' => "\u{1F510}",
                'description' => 'Password manager pre tím. Zdieľané heslá, secure notes, 2FA autentifikácia, audit logs, browser extensions.',
                'features' => ['Team password vault', 'Secure sharing', '2FA & audit logs', 'Browser extensions'],
                'category' => 'security',
                'sort_order' => 22,
            ],
            [
                'name' => 'Automation',
                'slug' => 'automation',
                'icon' => "\u{26A1}",
                'description' => 'Workflow automatizácia ako Zapier. Prepojenie aplikácií, automatické úlohy, triggery & actions, custom integrations.',
                'features' => ['Visual workflow editor', '100+ integrations', 'Triggers & actions', 'Custom webhooks'],
                'category' => 'tools',
                'sort_order' => 23,
            ],
            [
                'name' => 'Notes',
                'slug' => 'notes',
                'icon' => "\u{1F4D3}",
                'description' => 'Poznámky a zápisníky. Markdown support, organizácia do priečinkov, zdieľanie poznámok, full-text search.',
                'features' => ['Markdown editor', 'Folders & tags', 'Note sharing', 'Full-text search'],
                'category' => 'collaboration',
                'sort_order' => 24,
            ],
            [
                'name' => 'Tasks',
                'slug' => 'tasks',
                'icon' => "\u{2705}",
                'description' => 'To-do listy a task management. Priradenie úloh členom tímu, due dates, pripomienky, checklist items.',
                'features' => ['Task assignment', 'Due dates & reminders', 'Checklist items', 'Progress tracking'],
                'category' => 'collaboration',
                'sort_order' => 25,
            ],
            [
                'name' => 'Webtováreň Space',
                'slug' => 'space',
                'icon' => "\u{1F9E0}",
                'description' => 'Sledujte wellbeing vášho tímu. Predchádzajte vyhoreniu. Integrovaný systém manažmentu energie, nálady a produktivity.',
                'features' => ['Energy Tracking', 'Mood Monitoring', 'Burnout Alerts', 'Cloud Integration'],
                'category' => 'addon',
                'is_addon' => true,
                'sort_order' => 26,
            ],
        ];

        foreach ($services as $service) {
            Service::create($service);
        }
    }
}
